baseURL = "https://jetthoughts.com/"
canonifyURLs = true
languageCode = "en-us"
title = "JetThoughts"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = "beaver"
enableGitInfo = true
disableKinds = []

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  pages = "/:slug/"
  blog = "/blog/:slug/"

[permalinks.term]
  tags = "/blog/tags/:slug/"

[taxonomies]
    tag = "tags"

[build]
  writeStats = true

[imaging]
  quality = 80
  resampleFilter = "box"
  anchor = "smart"

[minify]
  minifyOutput = true

[[redirects]]
  from = "/tags/:slug/"
  to = "/blog/tags/:slug/"
  status = 301

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

[params]
  email="info@jetthoughts.com"
  phone="+1 754 216 9568"
  description="JetThoughts's expert team of developers and consultants has helped clients launch highly tailored projects, and we'd love to help you, too."
  copyright="© 2024 JetThoughts. All Rights Reserved."
  testimonials_heading = "Most clients stay over 3 years. Some stayed beyond 6."
  testimonials_description = "Don't just take our word for it. See what our clients say about our services."

  # GA4 Analytics Configuration
  googleAnalytics = "G-T1N27FC30F"
  privacyCompliant = true

[[params.testimonials]]
  name = "Bruno Wozniak"
  rating = 5
  title = "Director of Engineering at PubNative"
  description = "“Usually, in my experience, contractors are either highly talented but lacking in communication skills or vice versa. Guys from JetThoughts got the best of both worlds. They implemented easy ways to manage the flow of a distributed team and support high-quality code and development overall. Their team was also detailed and precise, helping us to find problems before they appear. We knew exactly what was happening and where we were going the whole time.”"

[menu]
[[menu.main]]
  identifier = "services"
  name = "Services"
  pageRef= "pages/services/"
  weight = 10

    [[menu.main]]
      parent = "services"
      identifier = "fractional-cto"
      title = "Fractional CTO"
      name = "Get on-demand access to a CTO to help guide your technical vision, accelerate team-building, and improve development team operations."
      pageRef= "/services/fractional-cto/"
      weight = 1

    [[menu.main]]
      parent = "services"
      identifier = "fractional-product"
      title = "Fractional Product Management"
      name = "Get on-demand access to a product expert to help design UX, plan & prioritize your roadmap, and manage development schedules."
      pageRef= "/services/fractional-product-management/"
      weight = 2

    [[menu.main]]
      parent = "services"
      identifier = "app-web"
      title = "App/Web Development"
      name = "Whether you’re a startup building new products or an established business upgrading existing systems, we help deliver positive outcomes."
      pageRef= "/services/app-web-development/"
      weight = 3

    [[menu.main]]
      parent = "services"
      identifier = "outsourced-developer"
      title = "Outsourced Developer Staffing"
      name = "Increase your development capacity & reduce administrative workloads with pre-trained engineers that are ready to deploy within weeks."
      pageRef= "/services/outsourced-developer-staffing/"
      weight = 4

    [[menu.main]]
      parent = "services"
      identifier = "software-qa"
      title = "Software AQA & Testing"
      name = "Accelerate development, streamline release cycles, and eliminate roadblocks with fully-managed software testing & QA services."
      pageRef= "/services/software-qa-cat/"
      weight = 5

    [[menu.main]]
      parent = "services"
      identifier = "talent-recruiting"
      title = "Talent Recruiting & Training"
      name = "Scale your development team & simplify the talent acquisition process with top-caliber candidates that are pre-vetted by our team."
      pageRef= "/services/talent-recruiting-training/"
      weight = 6

[[menu.main]]
  identifier = "usecases"
  name = "Use Cases"
  pageRef= "pages/use-cases/"
  weight = 20

    [[menu.main]]
      parent = "usecases"
      identifier = "startup-mvp"
      title = "Startup MVP Prototyping & Development"
      name = "Whether creating an interactive prototype to validate the user experience or building out a Minimum Viable Product (MVP) for initial customers, we help startups accelerate the path from idea to revenue."
      pageRef= "/use-cases/startup-mvp-prototyping-development/"
      weight = 1

    [[menu.main]]
      parent = "usecases"
      identifier = "salvage-project"
      title = "Salvage an Existing Project"
      name = "The sooner a software project is salvaged, the better chance it has of being a viable long-term investment. We can help transform your product, providing the visibility, clarity, and control you need to get your project on track."
      pageRef= "/use-cases/salvage-existing-project/"
      weight = 2

    [[menu.main]]
      parent = "usecases"
      identifier = "empower-team"
      title = "Empower an Existing Engineering Team"
      name = "The easiest & fastest way to grow software development capacity is by using a trusted technology partner that can deploy pre-trained developers on-demand without the need for additional supervision."
      pageRef= "/use-cases/empower-existing-engineering-team/"
      weight = 3

    [[menu.main]]
      parent = "usecases"
      identifier = "emergency-cto"
      title = "Emergency CTO Leadership"
      name = "To maintain visibility, accountability, and control over technology outcomes when a critical team member leaves, companies need on-demand access to technical leadership to help keep the status quo for IT intact."
      pageRef= "/use-cases/emergency-cto-leadership/"
      weight = 4

    [[menu.main]]
      parent = "usecases"
      identifier = "automate-product"
      title = "Automate Product QA & Testing"
      name = "To enable faster product development while eliminating the risks of costly mistakes, companies need access to a reliable product testing & QA resource that can ensure quality at any scale."
      pageRef= "/use-cases/automate-product-qa-testing/"
      weight = 5

    [[menu.main]]
      parent = "usecases"
      identifier = "accelerate-dev"
      title = "Accelerate Development & Maximize Capacity"
      name = "Our developers are ready to deploy within weeks (not months), giving companies the ability to accelerate their software development process while still maintaining control over engineering quality."
      pageRef= "/use-cases/accelerate-development-maximize-capacity/"
      weight = 6

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  pageRef= "blog/"
  weight = 25

[[menu.main]]
  identifier = "about-us"
  name = "About Us"
  pageRef= "pages/about-us/"
  weight = 30

[[menu.main]]
  identifier = "clients"
  name = "Clients"
  pageRef= "pages/clients/"
  weight = 40

[[menu.main]]
  identifier = "careers"
  name = "Careers"
  pageRef = "pages/careers"
  weight = 50

[[menu.main]]
  identifier = "contact-us"
  name = "Contact Us"
  pageRef = "pages/contact-us"
  weight = 60

[[menu.services]]
  name = "Fractional CTO"
  url = "/services/fractional-cto/"
  weight = 10
[[menu.services]]
  name = "Fractional Product Management"
  url = "/services/fractional-product-management/"
  weight = 20
[[menu.services]]
  name = "Talent Recruiting & Training"
  url = "/services/talent-recruiting-training/"
  weight = 30
[[menu.services]]
  name = "App/Web Development"
  url = "/services/app-web-development/"
  weight = 40
[[menu.services]]
  name = "Outsourced Developer Staffing"
  url = "/services/outsourced-developer-staffing/"
  weight = 50
[[menu.services]]
  name = "Software QA & CAT"
  url = "/services/software-qa-cat/"
  weight = 60


[[menu.company]]
  name = "About Us"
  url = "/about-us/"
  weight = 10
[[menu.company]]
  name = "Contact Us"
  url = "/contact-us/"
  weight = 20
[[menu.company]]
  name = "Free Consultation"
  url = "/free-consultation/"
  weight = 30
[[menu.company]]
  name = "Careers <b class=\"special\">we’re hiring</b>"
  url = "/careers/"
  weight = 40

[[menu.resources]]
  name = "Clients"
  url = "/clients/"
  weight = 10
[[menu.resources]]
  name = "Use Cases"
  url = "/use-cases/"
  weight = 20


[params.forms.career]
action = "https://docs.google.com/forms/d/e/1FAIpQLSfHFrlRzMK2EdIKNNLJuo9Kl4O_eRHLwvOLKNP2d0y06d2YCQ/formResponse"
first_name = "entry.1569799146"
last_name = "entry.321887476"
email = "entry.59802721"
phone = "entry.1791744358"
linkedin = "entry.1769823274"
introduce = "entry.995298486"
position= "entry.1219121854"


[params.forms.contact]
action = "https://docs.google.com/forms/d/e/1FAIpQLSc-GYwOIET7_oVIXxsVmHfsaTlAi7aBA21aFVMVaqmXFl-S2Q/formResponse"
first_name = "entry.1054399299"
last_name = "entry.615737515"
email = "entry.577692471"
phone = "entry.1061724990"
tell = "entry.1791620687"


[params.forms.newsletter]
action = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSdD4751jeepeQe4wefgLqBO6XAU0qqvKWvmJ8P6xRmrMRvakg/formResponse"
email = "entry.939459641"
