baseURL = "http://localhost:1313/"
buildDrafts = true
buildExpired = true
buildFuture = true
environment = "development"

disableKinds = ["RSS", "sitemap", "robotsTXT"]

[build]
  noJSConfigInAssets = true
  useResourceCacheWhen = "fallback"

[imaging]
  quality = 70
  resampleFilter = "box"
  anchor = "smart"

[minify]
  minifyOutput = false
