baseURL = "http://localhost:1313/"
buildDrafts = true
buildExpired = true
buildFuture = true

disableKinds = ["RSS", "sitemap", "robotsTXT"]

[build]
writeStats = false
noJSConfigInAssets = true
useResourceCacheWhen = "fallback"

[imaging]
quality = 70
resampleFilter = "box"
anchor = "smart"
