# Production Environment Configuration
# Optimizations for production builds

# Production environment settings
environment = "production"

# Enable all content types in production
disableKinds = []

# Production build optimizations
[build]
  # Optimized worker configuration for better performance
  numWorkers = 2  # Reduced to prevent memory spikes and timeouts
  writeStats = true

  # Cache configuration for faster rebuilds
  [build.buildStats]
    enable = true

# High-quality image processing for production
[imaging]
  quality = 80

# Enable minification in production
[minify]
  minifyOutput = true

# Production-specific parameters
[params]
  # Production environment
  environment = "production"

[outputs]
    home = ["HTML"]  # Only build HTML, skip JSON/RSS in tests
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]
