---
# Simplified Docker Compose configuration for JetThoughts Hugo development
# Optimized for fast feedback loops with minimal complexity

services:
  hugo:
    image: hugomods/hugo:exts-non-root-0.149.1
    working_dir: /app
    volumes:
      - ..:/app:delegated
      - hugo_cache:/tmp/hugo_cache
    ports:
      - '1313:1313'
    command: server --bind 0.0.0.0 --poll 500ms --disableFastRender=false
    environment:
      HUGO_CACHEDIR: /tmp/hugo_cache
      HUGO_NUMWORKERMULTIPLIER: 8
      HUGO_ENABLEGITINFO: false
    restart: unless-stopped
    mem_limit: 512m
    cpus: '2.0'

  # Interactive shell (optimized)
  sh:
    image: jetthoughts.com-test:1.0.0
    build:
      context: ../
      dockerfile: ./.dev/Dockerfile
      target: runtime
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ..:/app:delegated
      - bundle:/opt/bundle
      - history:/usr/local/hist
    environment:
      HISTFILE: /usr/local/hist/.bash_history
      IRB_HISTFILE: /usr/local/hist/.irb_history
      BUNDLE_PATH: /opt/bundle
    command: sh

  # Test runner with optimized dependency management
  t:
    image: jetthoughts.com-test:1.0.0
    build:
      context: ../
      dockerfile: ./.dev/Dockerfile
      target: runtime
    working_dir: /app
    command: bin/test
    volumes:
      - ..:/app:delegated
      - node_modules:/app/node_modules
      - bundle:/opt/bundle
      - hugo_cache_dtest:/tmp/hugo_cache_dtest
    environment:
      HUGO_DEFAULT_PATH: "_dest/public-dtest"
      HUGO_CACHEDIR: "/tmp/hugo_cache_dtest"
      HUGO_ENABLEGITINFO: "false"
      TEST_QUIET: "true"
      CAPYBARA_SCREENSHOT_ON_FAILURE: "true"
      PARALLEL_TEST_PROCESSORS: 4
      RUBY_THREAD_VM_STACK_SIZE: 1048576
    mem_limit: 2g
    cpus: '4.0'
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  node_modules:
    driver: local
  bundle:
    driver: local
  history:
    driver: local
  hugo_cache:
    driver: local
  hugo_cache_dtest:
    driver: local
