---
# Simplified Docker Compose configuration for JetThoughts Hugo development
# Optimized for fast feedback loops with minimal complexity

services:
  # Hugo development server (port 1313)
  hugo:
    image: hugomods/hugo:exts-non-root-0.149.1
    working_dir: /app
    volumes:
      - ..:/app:delegated
    ports:
      - '1313:1313'
    command: hugo server --bind 0.0.0.0 --poll 1s
    environment:
      HUGO_CACHEDIR: /app/.hugo_cache
    restart: unless-stopped

  # Hugo watch mode for tests (build-only, no server)
  hugo-watch:
    image: hugomods/hugo:exts-non-root-0.149.1
    working_dir: /app
    volumes:
      - ..:/app:delegated
    command: 
      - hugo
      - --destination=public-dtest
      - --environment=production
      - --watch
      - --poll=1s
    environment:
      HUGO_CACHEDIR: /app/.hugo_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/app/public-dtest/index.html"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 60s

  # Interactive shell
  sh:
    image: jetthoughts.com-test:1.0.0
    build:
      context: ../
      dockerfile: ./.dev/Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ..:/app:delegated
      - /app/node_modules
      - bundle:/opt/bundle
      - history:/usr/local/hist
    environment:
      HISTFILE: /usr/local/hist/.bash_history
      IRB_HISTFILE: /usr/local/hist/.irb_history
      BUNDLE_PATH: /opt/bundle
    command: bash

  # Test runner with Hugo dependency
  t:
    image: jetthoughts.com-test:1.0.0
    build:
      context: ../
      dockerfile: ./.dev/Dockerfile
    working_dir: /app
    command: bin/test
    depends_on:
      hugo-watch:
        condition: service_healthy
    volumes:
      - ..:/app:delegated
      - /app/node_modules
      - bundle:/opt/bundle
      - test_screenshots:/app/tmp/screenshots
    environment:
      HUGO_DEFAULT_PATH: "public-dtest"
      CAPYBARA_SCREENSHOT_ON_FAILURE: "true"
      CHROME_FLAGS: "--disable-gpu --no-sandbox --disable-dev-shm-usage"

volumes:
  bundle:
  history:
  test_screenshots: