---
x-backend: &backend
  image: jetthoughts.com-test:1.0.0
  build:
    context: ../
    dockerfile: ./.dev/Dockerfile
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - node_modules:/app/node_modules
    - history:/usr/local/hist
  environment:
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history

services:
  hugo:
    image: hugomods/hugo:exts-non-root-0.145.0
    stdin_open: true
    tty: true
    volumes:
      - ..:/src:cached
      - hugo_cache:/tmp/hugo_cache
    ports:
      - '1313:1313'
    command: server --bind 0.0.0.0

  sh:
    <<: *backend
    command: sh

  t:
    <<: *backend
    entrypoint: bin/test
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '1GB'
        reservations:
          cpus: '1.5'
          memory: '512M'
volumes:
  bundle:
  history:
  node_modules:
  hugo_cache:
