---
x-backend: &backend
  image: jetthoughts.com-test:1.0.0
  build:
    context: ../
    dockerfile: ./.dev/Dockerfile
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - history:/usr/local/hist
  environment:
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history

services:
  hugo: &hugo
    image: hugomods/hugo:exts-non-root-0.149.1
    stdin_open: true
    tty: true
    volumes:
      - ..:/src:cached
      - hugo_cache:/tmp/hugo_cache
    ports:
      - '1313:1313'
    command: server --bind 0.0.0.0

  sh:
    <<: *backend
    command: bash

  t-setup:
    <<: *hugo
    command: hugo --minify --environment production --forceSyncStatic --cleanDestinationDir --logLevel warn

  t:
    <<: *backend
    entrypoint: bin/test
    shm_size: 256mb  # Shared memory size for Chrome browser
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '2GB'  # Increased for Chrome browser stability
        reservations:
          cpus: '1.5'
          memory: '1GB'  # Increased base reservation

    depends_on:
      t-setup:
        condition: service_completed_successfully
volumes:
  bundle:
  history:
  hugo_cache:
