---
x-backend: &backend
  image: jetthoughts.com-test:1.0.0
  build:
    context: .
    dockerfile: ./Dockerfile
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - bundle:/app/vendor/bundle
    - node_modules:/app/node_modules
    - history:/usr/local/hist
  environment:
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history

services:
  sh:
    <<: *backend
    command: sh

  t:
    <<: *backend
    entrypoint: bin/test

volumes:
  bundle:
  history:
  node_modules:
