# This is a basic workflow that is manually triggered

name: Sync all dev.to articles

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Make script executable
      run: chmod +x bin/from_devto
    - name: Create content/blog catalog
      run: mkdir content/blog
    - name: Run sync script
      run: bin/from_devto -f

