---
name: Sync dev.to articles

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 4-21 * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'Synchronize all posts.'
        required: true
        default: false

permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sync script
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        run: |
          if [ "${{ github.event.inputs.force }}" = "true" ]
          then
            bin/from_devto -f
          else
            bin/from_devto
          fi
          
          bin/upload_assets_to_github

      - name: Commit and push if it changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Update blog content'; git push)
