# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Sync articles"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: ${{ github.event.pull_request.number != '' }}

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    uses: ./.github/workflows/_hugo.yml
