name: Deploy Pull Request to Surge

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Deploy to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_EMAIL }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          DEPLOY_URL="https://${PR_NUMBER}-your-project.surge.sh"
          surge --project ./build --domain $DEPLOY_URL

      - name: Add comment with Surge link
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          DEPLOY_URL="https://${PR_NUMBER}-your-project.surge.sh"
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"🚀 Deployed to Surge: $DEPLOY_URL\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
